### ISSUE TITLE
Launcher doesn't detect installed game

### ISSUE THREAD

**Issue by danieleremin** [QwertyTheCoder/Minecraft-Bedrock-Crack#11]
I installed the game but it doesn't detect it and says to install it.

Minecraft is not installed. Install it using install appx  or install appx at custom location

**Comment by QwertyTheCoder** [comment]
@danieleremin i will add a new and different client as soon as possible within 2 days

**Comment by QwertyTheCoder** [comment]
https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked
