### ISSUE TITLE
Freezing Problem

### ISSUE THREAD

**Issue by ZarghamMahi** [QwertyTheCoder/Minecraft-Bedrock-Crack#12]
Sometimes (not every time), When the timer restarts, the game freezes.

**Comment by QwertyTheCoder** [comment]
@ZarghamMahi Sorry for my late reply mate...

To fix this problem
1. Navigate to the command line of m centres
2. Write down ".timer = 99999999"
3. If doesn't works write "timer = 99999999"
4. Start minecraft

If this doesn't works, reply to this comment

**Comment by QwertyTheCoder** [comment]
@ZarghamMahi Did it worked?
