### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by jasonly28** [QwertyTheCoder/Minecraft-Bedrock-Crack#13]
DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by QwertyTheCoder** [comment]
@jasonly28 press "disable hack"
and use this
https://github.com/QwertyTheCoder/Minecraft-Bedrock-Cracked

**Comment by jasonly28** [comment]
@QwertyTheCoder i did it and it gives me this error unsupported version  @22621.1194

**Comment by QwertyTheCoder** [comment]
@jasonly28 Create a issue in 
https://github.com/QwertyTheCoder/Minecraft-Bedrock-Cracked
