### ISSUE TITLE
Wait a few moments Minecraft is not installed. Install it using install appx  or install appx at custom location

### ISSUE THREAD

**Issue by Thandibirani** [QwertyTheCoder/Minecraft-Bedrock-Crack#15]
Please resolve this issue

**Comment by Thandibirani** [comment]
And installing Microsoft.VCLibs.140.00_1
![Screenshot (6)](https://user-images.githubusercontent.com/130365466/230894441-ec178cda-bcb8-4af8-b7f5-b7307b4b33ab.png)
4.0.30704.0_x64__8wekyb3d8bbwe

**Comment by QwertyTheCoder** [comment]
@Thandibirani Since, you have windows 11
so, it wont make a difference if you dont install it. cause its already installed.
