### ISSUE TITLE
I got this error when attempting to launch. Help?

### ISSUE THREAD

**Issue by IntoTheVoid-900** [QwertyTheCoder/Minecraft-Bedrock-Crack#3]
Unknown error (0x87b20c15)
The error code is -2147467259
The source is System

**Comment by QwertyTheCoder** [comment]
hello can you contact me

**Comment by QwertyTheCoder** [comment]
did you done it step by step

**Comment by IntoTheVoid-900** [comment]
?

**Comment by QwertyTheCoder** [comment]
can you contact me on discord

**Comment by IntoTheVoid-900** [comment]
Your discord name is too long, it dosent show the numbers

**Comment by IntoTheVoid-900** [comment]
Add me, I am Darkblade360350#2122
