### ISSUE TITLE
Not able to load older versions 

### ISSUE THREAD

**Issue by KnightxMare** [QwertyTheCoder/Minecraft-Bedrock-Crack#4]
The latest 1.18 works fine but when I try to change to older versions like 1.16 or something I get "DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand"
Did everything Step by Step and also reinstalled the version to get the same error

**Comment by QwertyTheCoder** [comment]
Hello
This error can be caused by developer options of windows, try to turn off and turn on again developer options of windows and then restart.
If it doesn't works you can contact me in discord
