### ISSUE TITLE
MCLauncher not opening

### ISSUE THREAD

**Issue by BerBerOnGithub** [QwertyTheCoder/Minecraft-Bedrock-Crack#6]
For some reason, MCLauncher is not opening.

**Comment by HerbertRuan** [comment]
Estou com o mesmo problema . alguem conseguiu resolver isso ?

**Comment by QwertyTheCoder** [comment]
@BerBerOnGithub @HerbertRuan i will add a new and different client as soon as possible within 2 days

**Comment by QwertyTheCoder** [comment]
@BerBerOnGithub @HerbertRuan https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked
