### ISSUE TITLE
Game automatically crash in game. 

### ISSUE THREAD

**Issue by Arunkapil01** [QwertyTheCoder/Minecraft-Bedrock-Crack#8]
After like 30-40 minutes game automatically gets freezed and I have to restart the game to play it. It's annoying how to fix this issue?

**Comment by Pler123** [comment]
I have the same issue can anyone help?

**Comment by Pler123** [comment]
Also it is faster it happens like every 10 minutes

**Comment by QwertyTheCoder** [comment]
@Arunkapil01 @Pler123 i will add a new client as soon as possible

**Comment by QwertyTheCoder** [comment]
@Arunkapil01 @Pler123 https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked
