### ISSUE TITLE
deployment error when installing, already did prerequesites 

### ISSUE THREAD

**Issue by SpectralSen** [QwertyTheCoder/Minecraft-Bedrock-Crack#9]
DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by MTM828** [comment]
Forget this, this is rubbish.
Go with a launcher like PortableMC (JE), MultiMC (JE), Pojav (JE on Android/IOS), MCPE Launcher (BE Pocket edition on PC).

**Comment by Rxmsey** [comment]
> 

do you know how do you install the package through these launchers, protable for example

**Comment by QwertyTheCoder** [comment]
@Rxmsey @MTM828 @SpectralSen i will add a new and different client as soon as possible within 2 days

**Comment by QwertyTheCoder** [comment]
@Rxmsey @MTM828 @SpectralSen https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked
